codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "50...90"

  status:
    project:
      default:
        threshold: 1%

    patch:
      default:
        threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, footer"
  behavior: "new"		# delete old, post new
