version: 2
jobs:
  build:
    branches:
      only:
        - master
jobs:
  build:
    machine: 
      enabled: true
    environment:
      - ZFS_BUILD_TAGS=0
    # working_directory: github.com/Pradeepkumarbk/zfs1
    steps:
      - checkout
      - run: pwd
      - run:
          command: |     
            sudo apt-get update
            sudo apt-get install bc
            sudo apt-get install git -y
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository --yes ppa:zfs-native/stable
            sudo apt-get update
            #sudo apt-get install -y ubuntu-zfs
            sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get install gcc-snapshot -y
            sudo apt-get update
            sudo apt-get install gcc-6 g++-6 -y
            sudo apt-get update
            sudo apt-get install -y build-essential autoconf libtool gawk alien fakeroot linux-headers-$(uname -r) libaio-dev
            sudo apt-get install -y zlib1g-dev uuid-dev libattr1-dev libblkid-dev libselinux-dev libudev-dev libssl-dev
            sudo apt-get install -y lcov libjemalloc-dev
            sudo apt-get install -y parted lsscsi ksh attr acl nfs-kernel-server fio
            sudo apt-get install -y libgtest-dev cmake
            sudo apt-get install -y gdb
            sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
            sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-6 /usr/bin/g++
            pushd .
            cd /usr/src/gtest
            sudo cmake CMakeLists.txt
            sudo make -j4
            sudo cp *.a /usr/lib
            popd
            cd ..
            #apt-get install git -y
            git clone https://github.com/axboe/fio
            cd fio
            git checkout 2e4ef4fbd69eb6d4c07f2f362463e3f3df2e808c
            ./configure
            make -j4
            cd ..
            git clone https://github.com/openebs/spl
            cd spl
            git checkout spl-0.7.4
            sh autogen.sh
            ./configure
            if [ "$ZFS_BUILD_TAGS" = "0" ]; then
              make -j4;
            fi
            cd ../zfs1
            sh autogen.sh
            if [ "$ZFS_BUILD_TAGS" = "0" ]; then
              ./configure --with-config=user --enable-code-coverage=yes --enable-debug --enable-uzfs=yes --with-jemalloc --with-fio=$PWD/../fio || true;
              make -j4;
            fi
            make cstyle;
            if [ "$ZFS_BUILD_TAGS" = "0" ]; then
              export FIO_SRCDIR=$PWD/../fio;
              sudo bash ./tests/cbtest/script/test_uzfs.sh -T all ;
            fi

