version: 2
jobs:
  build:
    docker:
      - image: ubuntu:14.04
    environment:
      # - ZFS_BUILD_TAGS=0
      - ZFS_BUILD_TAGS=1
    working_directory: github.com/Pradeepkumarbk/zfs1
    steps:
      - checkout
      - run: printf "%f,$ZFS_BUILD_TAGS"
      - run: pwd
      - run: ls 
      - run:
          command: |
            uname -mrs       
            apt-cache search linux-generic
            apt-get update
            apt-get install bc
            apt-get install -y software-properties-common
            apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/* 
            apt-get update 
            sudo apt-get install git -y
            sudo apt install -y linux-generic dkms git
            git clone https://github.com/snuf/iomemory-vsl.git
            sudo cp -r iomemory-vsl/root/usr/src/iomemory-vsl-3.2.10 /usr/src/
            sudo mkdir -p /var/lib/dkms/iomemory-vsl/3.2.10/build
            sudo ln -s /usr/src/iomemory-vsl-3.2.10 /var/lib/dkms/iomemory-vsl/3.2.10/source
            sudo dkms build -m iomemory-vsl -v 3.2.10
            sudo dkms install -m iomemory-vsl -v 3.2.10
            sudo modprobe iomemory-vsl
            wget https://github.com/promisejohn/fio-driver/raw/master/utils/fio-util_3.2.10.1509-1.0_amd64.deb
            sudo dpkg -i fio-util_3.2.10.1509-1.0_amd64.deb 
            sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get install gcc-snapshot -y
            sudo apt-get update
            sudo apt-get install gcc-6 g++-6 -y
            sudo apt-get update
            sudo apt-get install -y build-essential autoconf libtool gawk alien fakeroot linux-headers-$(uname -r) libaio-dev
            sudo apt-get install -y zlib1g-dev uuid-dev libattr1-dev libblkid-dev libselinux-dev libudev-dev libssl-dev
            sudo apt-get install -y lcov libjemalloc-dev
            sudo apt-get install -y parted lsscsi ksh attr acl nfs-kernel-server fio
            sudo apt-get install -y libgtest-dev cmake
            sudo apt-get install -y gdb
            sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
            sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-6 /usr/bin/g++
            pushd .
            cd /usr/src/gtest
            sudo cmake CMakeLists.txt
            sudo make -j4
            sudo cp *.a /usr/lib
            popd
            cd ..
            # sudo apt-get install git -y
            git clone https://github.com/axboe/fio
            cd fio
            git checkout 2e4ef4fbd69eb6d4c07f2f362463e3f3df2e808c
            ./configure
            make -j4
            cd ..
            git clone https://github.com/openebs/spl
            cd spl
            git checkout spl-0.7.4
            sh autogen.sh
            ./configure
            if [ "$ZFS_BUILD_TAGS" = "1" ]; then
              make --no-print-directory -s pkg-utils pkg-kmod;
              sudo dpkg -i *.deb;
            fi
            cd ../zfs1
            sh autogen.sh
            if [ "$ZFS_BUILD_TAGS" = "1" ]; then
              ./configure --enable-code-coverage=yes --enable-debug || true;
              make --no-print-directory -s pkg-utils pkg-kmod || true;
              sudo dpkg -i *.deb || true;
            fi
            make cstyle;
            # chmod -R 744 cmd/mount_zfs/Makefile.am
            if [ "$ZFS_BUILD_TAGS" = "1" ]; then
              sudo sbin/modprobe zfs;
              timeout 10 sbin/ztest || true;
            fi


            
