version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    environment:
      - ZFS_BUILD_TAGS=0
      - ZFS_BUILD_TAGSS=1
    working_directory: github.com/Pradeepkumarbk/zfs1
    steps:
      - checkout
      - run: printf "%f,$ZFS_BUILD_TAGS"
      - run: pwd
      - run: ls 
      - run:
          command: |     
            apt-get update
            apt-get install bc
            apt-get install -y software-properties-common
            add-apt-repository --yes ppa:ubuntu-toolchain-r/test
            apt-get update
            apt-get install gcc-snapshot -y
            apt-get update
            apt-get install gcc-6 g++-6 -y
            apt-get update
            apt-get install -y build-essential autoconf libtool gawk alien fakeroot linux-headers-$(uname -r) libaio-dev
            apt-get install -y zlib1g-dev uuid-dev libattr1-dev libblkid-dev libselinux-dev libudev-dev libssl-dev
            apt-get install -y lcov libjemalloc-dev
            apt-get install -y parted lsscsi ksh attr acl nfs-kernel-server fio
            apt-get install -y libgtest-dev cmake
            apt-get install -y gdb
            unlink /usr/bin/gcc && ln -s /usr/bin/gcc-6 /usr/bin/gcc
            unlink /usr/bin/g++ && ln -s /usr/bin/g++-6 /usr/bin/g++
            pushd .
            cd /usr/src/gtest
            cmake CMakeLists.txt
            make -j4
            cp *.a /usr/lib
            popd
            cd ..
            apt-get install git -y
            git clone https://github.com/axboe/fio
            cd fio
            git checkout 2e4ef4fbd69eb6d4c07f2f362463e3f3df2e808c
            ./configure
            make -j4
            cd ..
            git clone https://github.com/openebs/spl
            cd spl
            git checkout spl-0.7.4
            sh autogen.sh
            ./configure
            if [ "$ZFS_BUILD_TAGSS" = "1" ]; then
              make --no-print-directory -s pkg-utils pkg-kmod;
              dpkg -i *.deb;
            fi
            cd ../zfs1
            sh autogen.sh
            # dpkg -i --force linux-image-3.13.0-83-generic_3.13.0-83.127_amd64.deb
            apt install -y zfsutils-linux
            dpkg -i --force linux-image-3.13.0-83-generic_3.13.0-83.127_amd64.deb
            if [ "$ZFS_BUILD_TAGSSS" = "1" ]; then
              ./configure --enable-code-coverage=yes --enable-debug || true;
              make --no-print-directory -s pkg-utils pkg-kmod || true;
              dpkg -i *.deb || true;
            fi
            if [ "$ZFS_BUILD_TAGSS" = "1" ]; then
              /sbin/modprobe zfs;
              timeout 10 /sbin/ztest || true;
            fi
            
