version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    environment:
      ZFS_BUILD_TAGS=0
      ZFS_BUILD_TAGS=1
    steps:
      - checkout
      - run: apt-get update 
      - run: apt-get install software-properties-common
      - run: add-apt-repository ppa:ubuntu-toolchain-r/test
      - run: apt-get install --yes gcc-6 g++-6
      - run: sudo apt-get install --yes -qq build-essential autoconf libtool gawk alien fakeroot linux-headers-$(uname -r) libaio-dev
      - run: sudo apt-get install --yes -qq zlib1g-dev uuid-dev libattr1-dev libblkid-dev libselinux-dev libudev-dev libssl-dev
      - run: sudo apt-get install --yes -qq lcov libjemalloc-dev
      # packages for tests
      - run: sudo apt-get install --yes -qq parted lsscsi ksh attr acl nfs-kernel-server fio
      - run: sudo apt-get install --yes -qq libgtest-dev cmake
      # packages for debugging
      - run: sudo apt-get install gdb
      # use gcc-6 by default
      - run: sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
      - run: sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-6 /usr/bin/g++
      - run: pushd .
      - run: cd /usr/src/gtest
      - run: sudo cmake CMakeLists.txt
      - run: sudo make -j4
      - run: sudo cp *.a /usr/lib
      - run: popd
      - run: cd ..
      # we need fio repo to build zfs replica fio engine
      - run: git clone https://github.com/axboe/fio
      - run: cd fio
      # TODO: replace commit hash by version tag in future
      - run: git checkout 2e4ef4fbd69eb6d4c07f2f362463e3f3df2e808c
      - run: ./configure
      - run: make -j4
      - run: cd ..
      - run: git clone https://github.com/openebs/spl
      - run: cd spl
      - run: git checkout spl-0.7.4
      - run: sh autogen.sh
      - run: ./configure
      - run: if [ $ZFS_BUILD_TAGS = 0 ]; then
              make -j4;
            else
              make --no-print-directory -s pkg-utils pkg-kmod;
              dpkg -i *.deb;
            fi
      - run: cd ../zfs
      - run: sh autogen.sh
      - run: if [ $ZFS_BUILD_TAGS = 0 ]; then
              ./configure --with-config=user --enable-code-coverage=yes --enable-debug --enable-uzfs=yes --with-jemalloc --with-fio=$PWD/../fio || true;
              make -j4;
            else
              ./configure --enable-code-coverage=yes --enable-debug || true;
              make --no-print-directory -s pkg-utils pkg-kmod || true;
              dpkg -i *.deb || true;
            fi
      - run: make cstyle;
      # run ztest and test supported zio backends
      # XXX enable the ztest when ticket #152 is fixed
      - run: if [ $ZFS_BUILD_TAGS = 0 ]; then
             export FIO_SRCDIR=$PWD/../fio;
             timeout 60 sudo bash ./tests/cbtest/script/test_uzfs.sh -T all || true;
           else
             sudo /sbin/modprobe zfs;
             timeout 10 /sbin/ztest || true;
           fi
