version: 2
jobs:
  build:
    docker:
      - image: ubuntu:14.04
    environment:
      - ZFS_BUILD_TAGS=0
    working_directory: github.com/Pradeepkumarbk/zfs1
    steps:
      - checkout
      - run: printf "%f,$ZFS_BUILD_TAGS"
cljs_test:
  docker:
    - image: ubuntu:14.04 
      environment:
        - ZFS_BUILD_TAGS=1
  working_directory: github.com/Pradeepkumarbk/zfs1
  steps:
    - checkout
    - run: printf "%f,$ZFS_BUILD_TAGS"
     
